apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: dev-platform

nameSuffix: -dev

commonLabels:
  platform.blueprint/environment: development

patches:
  - path: patches/replicas.yaml
