apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-app-deployment
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: secure-app-container
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
