apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: platform-app-monitor
  labels:
    platform.blueprint/component: monitoring
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: secure-app
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
