apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - patches/pdb.yaml

namespace: prod-platform

nameSuffix: -prod

commonLabels:
  platform.blueprint/environment: production

patches:
  - path: patches/replicas-resources.yaml
